#version: '3.8'
#
#services:
#  mysql:
#    container_name: MySQL
#    image: mysql/mysql-server
#    environment:
#      MYSQL_USER: root
#      MYSQL_PASSWORD: Switch@906
#      MYSQL_DATA_DIR: /data/mysql
#    volumes:
#      - mysql:/data/mysql
#    ports:
#      - "3307:3306"
#    networks:
#      - mysql
#    restart: unless-stopped
#networks:
#  mysql:
#    driver: bridge
#
#volumes:
#  mysql:
#    driver: local

version: '3.18'

services:

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres

  pg_admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: hello@example.com
      PGADMIN_DEFAULT_PASSWORD: world


    # app:
    #   build:
    #   image : springboot-example
    #   ports:
    #     - "8080:8080"
    #   depends_on:
    #     - postgres_db
    #   networks:
    #     - local



networks:
  local:
    name: local
    driver: bridge

